const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],HISTORY_KEY="scamshield_history_v1";let currentType="text";
const signalRules=[
{name:"Urgency Language",icon:"◷",weight:18,severity:"High",test:s=>/(urgent|immediately|act now|limited time|hurry|blocked|suspended|expire|last chance)/i.test(s),detail:'Pressure words such as "urgent" or "act now"'},
{name:"OTP / Password Request",icon:"🔒",weight:30,severity:"High",test:s=>/(otp|one[- ]time password|password|pin|cvv|verification code|security code)/i.test(s),detail:"Requests sensitive authentication information"},
{name:"Suspicious Link Detected",icon:"🔗",weight:22,severity:"High",test:s=>/(https?:\/\/|www\.|bit\.ly|tinyurl|\.xyz\b|\.top\b|\.click\b|\.ru\b)/i.test(s),detail:"Contains a link or risky-looking domain"},
{name:"Prize / Giveaway Scam",icon:"★",weight:22,severity:"Medium",test:s=>/(congratulations|winner|won a|free iphone|free gift|prize|giveaway|claim reward|lottery)/i.test(s),detail:"Unexpected prize or reward language"},
{name:"Financial Request",icon:"₹",weight:22,severity:"High",test:s=>/(send money|transfer|bank details|account number|upi|payment|gift card|crypto|refund fee|processing fee)/i.test(s),detail:"Asks for money or banking information"},
{name:"Threat / Account Fear",icon:"!",weight:16,severity:"High",test:s=>/(account.*(closed|locked|blocked|suspended)|police|legal action|fine|penalty|arrest)/i.test(s),detail:"Uses fear or account-threat language"},
{name:"Personal Data Request",icon:"♙",weight:20,severity:"High",test:s=>/(aadhaar|pan card|date of birth|address|personal details|identity|kyc)/i.test(s),detail:"Requests identity or personal information"},
{name:"Impersonation Pattern",icon:"◉",weight:14,severity:"Medium",test:s=>/(bank team|customer care|support team|government officer|police officer|ceo|manager)/i.test(s),detail:"Claims to represent a trusted authority"}];
function analyzeText(text,type="text"){const s=(text||"").trim();if(!s)return{score:0,label:"Safe",signals:[],message:"No content provided."};const signals=signalRules.filter(r=>r.test(s));let score=signals.reduce((a,b)=>a+b.weight,0);if(type==="link"&&/https?:\/\//i.test(s))score+=8;if(/[A-Z]{7,}/.test(s))score+=5;if((s.match(/!/g)||[]).length>=3)score+=5;score=Math.min(100,score);let label=score>=70?"High":score>=40?"Medium":score>=18?"Low":"Safe";let message={High:"This content shows strong signs of being a scam or phishing attempt.",Medium:"This content has several suspicious signals. Verify it before acting.",Low:"A few warning signs were found. Stay cautious and verify independently.",Safe:"No strong scam patterns were detected by this demo."}[label];return{score,label,signals,message}}
function colorFor(r){return r.score>=70?"#ff3147":r.score>=40?"#f6b94b":"#20d79a"}
function renderHomeResult(r){$("#riskScore").textContent=r.score+"%";$("#riskLabel").textContent=r.label==="High"?"High Risk":r.label==="Medium"?"Medium Risk":r.label==="Low"?"Low Risk":"Low / Safe";$("#riskMessage").textContent=r.message;const d=r.score*3.6;$("#gauge").style.background=`conic-gradient(${colorFor(r)} ${d}deg,#202b34 ${d}deg)`;$("#riskAlert").textContent=r.score>=70?"⚠ Likely phishing/scam. Avoid links and personal information.":r.score>=40?"⚠ Verify the sender before taking action.":"✓ No strong pattern detected. Still verify unexpected requests.";$("#riskCount").textContent=`${r.signals.length} found`;$("#riskList").innerHTML=r.signals.length?r.signals.map(x=>`<div class="risk-item"><div class="r-icon">${x.icon}</div><div><strong>${x.name}</strong><small>${x.detail}</small></div><span class="severity ${x.severity==="Medium"?"medium":""}">${x.severity}</span></div>`).join(""):`<div class="empty-state">No major warning signals detected.</div>`}
function renderDetail(r,text,type){const s=r.score>=40?["Do not click unknown links","Do not share OTPs, passwords, PINs or CVV","Verify using the official website/app","Report suspicious accounts or numbers","Ask a trusted person before sending money"]:["Verify unexpected requests","Use official websites and apps","Keep 2FA enabled","Never reuse passwords"];$("#resultDetail").innerHTML=`<h2>Analysis Result</h2><div class="result-detail-grid"><div><div class="gauge" style="background:conic-gradient(${colorFor(r)} ${r.score*3.6}deg,#202b34 ${r.score*3.6}deg)"><div><strong>${r.score}%</strong><span>Risk Score</span></div></div><h3 style="color:${colorFor(r)}">${r.label} Risk</h3><p style="color:#9aa6b2">${r.message}</p></div><div><h3>Detected Risks</h3><div class="risk-list">${r.signals.length?r.signals.map(x=>`<div class="risk-item"><div class="r-icon">${x.icon}</div><div><strong>${x.name}</strong><small>${x.detail}</small></div><span class="severity ${x.severity==="Medium"?"medium":""}">${x.severity}</span></div>`).join(""):`<div class="empty-state">No strong warning signals found.</div>`}</div><h3>Our Suggestion</h3><div class="suggestion-list">${s.map(x=>`<div>✓ ${x}</div>`).join("")}</div></div></div>`}
function saveHistory(text,type,r){const h=JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]");h.unshift({id:Date.now(),type,text:text.slice(0,250),score:r.score,label:r.label,signals:r.signals.map(x=>x.name),date:new Date().toLocaleString()});localStorage.setItem(HISTORY_KEY,JSON.stringify(h.slice(0,100)));updateStats();renderHistory();renderReports()}
function runAnalysis(sel,detail=false){const el=$(sel);let text=el.value.trim();if(currentType==="image")text=$("#fileName").textContent||"uploaded screenshot";if(!text){alert("Please paste suspicious content first.");return}const r=analyzeText(text,currentType);renderHomeResult(r);renderDetail(r,text,currentType);saveHistory(text,currentType,r);if(detail)$("#resultDetail").scrollIntoView({behavior:"smooth"})}
$("#analyzeBtn").onclick=()=>runAnalysis("#messageInput");$("#analyzeBtn2").onclick=()=>runAnalysis("#messageInput2",true);$("#newScanBtn").onclick=()=>{$("#messageInput").value="";$("#charCount").textContent="0/2000";renderHomeResult({score:0,label:"Safe",signals:[],message:"Paste a message or link and run the analyzer."})};$("#messageInput").oninput=e=>$("#charCount").textContent=`${e.target.value.length}/2000`;
function showPage(name){$$('.page').forEach(p=>p.classList.remove('active'));($("#page-"+name)||$("#page-home")).classList.add('active');$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===name));$("#sidebar").classList.remove('open');if(name==='history')renderHistory();if(name==='reports')renderReports();window.scrollTo({top:0,behavior:'smooth'})}$$('[data-page]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();showPage(el.dataset.page)}));
function setType(type){currentType=type;$$('.tab,.scan-type').forEach(b=>b.classList.toggle('active',b.dataset.type===type));$("#imageUpload").classList.toggle('hidden',type!=="image");$("#messageInput2").classList.toggle('hidden',type==="image");const p={text:"Paste your suspicious message here...",email:"Paste the suspicious email content here...",link:"Paste the suspicious URL here...",image:""};$("#messageInput").placeholder=p[type];$("#messageInput2").placeholder=p[type]}$$('.tab,.scan-type').forEach(b=>b.onclick=()=>setType(b.dataset.type));
const examples={sms:"URGENT! Your bank account is blocked. Click http://verify-account.xyz immediately and enter your OTP.",email:"Dear customer, your account will be suspended today. Send your password and verification code to our support team immediately.",link:"http://free-prize-winner.top/claim-now",prize:"CONGRATULATIONS!!! You won a free iPhone. Pay a processing fee and send your bank details to claim the prize."};$$('[data-example]').forEach(b=>b.onclick=()=>{$("#messageInput2").value=examples[b.dataset.example];setType(b.dataset.example==='link'?'link':'text')});
$("#pickImageBtn").onclick=()=>$("#imageInput").click();$("#imageInput").onchange=e=>$("#fileName").textContent=e.target.files?.[0]?.name||"";
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function renderHistory(){const q=($("#historySearch")?.value||"").toLowerCase(),f=$("#historyFilter")?.value||"all";let data=JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]").filter(x=>(f==='all'||x.label===f)&&x.text.toLowerCase().includes(q));$("#historyBody").innerHTML=data.length?data.map(x=>`<tr><td>${x.type}</td><td>${escapeHtml(x.text.slice(0,70))}${x.text.length>70?'…':''}</td><td><span class="status-pill ${x.label}">${x.label}${x.label==='High'?' Risk':''}</span></td><td>${x.date}</td><td><button class="ghost small" onclick="viewHistory(${x.id})">View</button></td></tr>`).join(""):`<tr><td colspan="5" style="text-align:center;color:#7f8b96;padding:28px">No scans yet.</td></tr>`}
window.viewHistory=id=>{const x=JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]").find(i=>i.id===id);if(!x)return;currentType=x.type;$("#messageInput2").value=x.text;renderDetail(analyzeText(x.text,x.type),x.text,x.type);showPage('analyze');$("#resultDetail").scrollIntoView({behavior:'smooth'})};$("#historySearch").oninput=renderHistory;$("#historyFilter").onchange=renderHistory;$("#clearHistory").onclick=()=>{if(confirm('Clear all scan history?')){localStorage.removeItem(HISTORY_KEY);renderHistory();updateStats();renderReports()}};
function renderReports(){const h=JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]"),high=h.filter(x=>x.label==='High').length,safe=h.filter(x=>x.label==='Low'||x.label==='Safe').length;$("#reportTotal").textContent=h.length;$("#reportHigh").textContent=high;$("#reportSafe").textContent=safe;$("#reportRate").textContent=h.length?Math.round(high/h.length*100)+'%':'0%';const c={};h.forEach(x=>x.signals.forEach(s=>c[s]=(c[s]||0)+1));const rows=Object.entries(c).sort((a,b)=>b[1]-a[1]).slice(0,7),max=rows[0]?.[1]||1;$("#signalReport").innerHTML=rows.length?rows.map(([k,v])=>`<div class="signal-row"><span>${k}</span><div class="signal-bar"><i style="width:${v/max*100}%"></i></div><b>${v}</b></div>`).join(""):`<div class="empty-state">Run scans to generate analytics.</div>`}
function updateStats(){const h=JSON.parse(localStorage.getItem(HISTORY_KEY)||"[]");$("#statAnalyzed").textContent=(12548+h.length).toLocaleString();$("#statScams").textContent=(3921+h.filter(x=>x.label==='High').length).toLocaleString()}
$("#urlToolBtn").onclick=()=>{const u=$("#urlToolInput").value.trim();if(!u){alert('Enter a URL.');return}const r=analyzeText(u,'link');$("#urlToolOut").innerHTML=`<b>${r.label} risk — ${r.score}/100</b><br>${r.signals.map(x=>x.name).join(', ')||'No common warning signals detected.'}`};$("#headerBtn").onclick=()=>{const h=$("#headerInput").value.trim();if(!h){alert('Paste an email header.');return}let n=[];if(!/spf=pass/i.test(h))n.push('SPF pass not found');if(!/dkim=pass/i.test(h))n.push('DKIM pass not found');if(/reply-to:/i.test(h)&&/from:/i.test(h))n.push('Check whether From and Reply-To domains match');$("#headerOut").innerHTML=n.length?'⚠ '+n.join('<br>⚠ '):'✓ No obvious basic header warning found in this demo.'};
$("#menuBtn").onclick=()=>$("#sidebar").classList.toggle('open');$("#themeBtn").onclick=()=>{document.body.classList.toggle('light');$("#themeBtn").textContent=document.body.classList.contains('light')?'☀':'☾'};$("#loginBtn").onclick=()=>$("#loginModal").classList.add('open');$("#closeLogin").onclick=()=>$("#loginModal").classList.remove('open');$("#loginModal").onclick=e=>{if(e.target.id==='loginModal')$("#loginModal").classList.remove('open')};$("#loginForm").onsubmit=e=>{e.preventDefault();const name=$("#nameInput").value.trim()||'User';localStorage.setItem('scamshield_name',name);$("#profileName").textContent=name.split(' ')[0];$("#loginModal").classList.remove('open');alert('Demo profile created locally.')};$("#profileName").textContent=(localStorage.getItem('scamshield_name')||'Arfan').split(' ')[0];renderHomeResult({score:0,label:'Safe',signals:[],message:'Paste a message or link and run the analyzer.'});renderHistory();renderReports();updateStats();
